# Configuración del API Gateway para Móvil (api-gateway-movil)
server:
  port: 8087

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: authenticate-service
            uri: http://servicio-auth:8081
            predicates:
              - Path=/authenticate
            filters:
              - AddRequestHeader=X-Request-By, DanSON Gateway Service

          - id: control-service
            uri: http://servicio-control:8083
            predicates:
              - Path=/api/**
            filters:
              - AddRequestHeader=X-Request-By, DanSON Gateway Service

          - id: medicina-service
            uri: http://servicio-control:8083
            predicates:
              - Path=/api/medicina/**
            filters:
              - AddRequestHeader=X-Request-By, DanSON Gateway Service

          - id: reproducciones-service
            uri: http://servicio-control:8083
            predicates:
              - Path=/api/reproducciones/**
            filters:
              - AddRequestHeader=X-Request-By, DanSON Gateway Service
