# Configuración del API Gateway para la Web (api-gateway-ganaderia)
server:
  port: 8086

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://servicio-auth:8081
            predicates:
              - Path=/**
            filters:
              - AddRequestHeader=X-Request-By, DanSON Gateway Service


          - id: alimentacion-service
            uri: http://servicio-alimentacion:8082
            predicates:
              - Path=/api/alimentacion/**
            filters:
              - AddRequestHeader=X-Request-By, DanSON Gateway Service

          - id: area_service
            uri: http://servicio-alimentacion:8082
            predicates:
              - Path=/api/areas/**
            filters:
              - AddRequestHeader=X-Request-By, DanSON Gateway Service

          - id: ganado-service
            uri: http://servicio-alimentacion:8082
            predicates:
              - Path=/api/ganados/**
            filters:
              - AddRequestHeader=X-Request-By, DanSON Gateway Service

          - id: control-service
            uri: http://servicio-control:8083
            predicates:
              - Path=/api/**
            filters:
              - AddRequestHeader=X-Request-By, DanSON Gateway Service

          - id: medicina-service
            uri: http://servicio-control:8083
            predicates:
              - Path=/api/medicina/**
            filters:
              - AddRequestHeader=X-Request-By, DanSON Gateway Service

          - id: reproducciones-service
            uri: http://servicio-control:8083
            predicates:
              - Path=/api/reproducciones/**
            filters:
              - AddRequestHeader=X-Request-By, DanSON Gateway Service
